# Generated by Django 3.2.3 on 2024-03-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписку', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
